### ISSUE TITLE
why I got same values in the whole map?

### ISSUE THREAD

**Issue by AJFeng** [bsmurphy/PyKrige#101]
I have some elevation data that collected in a field. This field had two sections (but they were just near to each other). The elevation in this two sections were different. The section 1 was low, and the section 2 was high. Yes, the elevation is the data what I want from the kriging. I have about 1500 elevation data for the input of kriging and want to estimate the elevation grid of 1500*2000.

When I run the Ordinary Kriging for S1 and S2 separately, the results were good, almost the same results with Arcgis. But when I run Ordinary Kriging  for the whole field, I got same values everywhere in the whole field. But I used the same code almost. Why this situation happened?

Is it because there are too much difference between these two sections even though they are near by each other geographically? I also tried to change the variogram_model, still same values everywhere. Do you have any ideas why this would happened and how to fixed this problem?

Thanks

**Comment by AJFeng** [comment]
Sorry about this question. I made a mistake that I input the wrong lat and long. I already figured it out. Thanks.

**Comment by bsmurphy** [comment]
OK cool, glad you figured it out. Closing out this issue.
