### ISSUE TITLE
Add a documentation page

### ISSUE THREAD

**Issue by rth** [bsmurphy/PyKrige#14]
It would be great to add a documentation page for PyKrige with [sphinx](http://www.sphinx-doc.org/en/stable/) hosted, for instance at [readthedocs.org](https://readthedocs.org/). 

The code itself is fairly well documented so it's just a matter of setting sphinx up and checking that the docstrings are correctly parsed. We could use, for instance, numpy style docstrings through [`sphinxcontrib-napoleon`](https://pypi.python.org/pypi/sphinxcontrib-napoleon) (some adaptation work might be necessary).

P.S: @bsmurphy could you please grant me collaborator's right on this repo, so I can assign labels on issues etc.  ?  Thanks.

**Comment by bsmurphy** [comment]
Sorry for the very delayed response to this... PhD stuff has kept me exceptionally busy recently. Anyways, I think this is a really good idea. I'm going to group this into a longer to-do list that I've been accumulating over the past few months... Also, just sent you an invite for collaborator status.
