### ISSUE TITLE
Cannot set backend to "C"

### ISSUE THREAD

**Issue by wind-chh** [bsmurphy/PyKrige#20]
I use the latest PyKrige (1.3.0) on Fedora 23, and everythong works well. But it cannot work with backend="C". 

Following is the error message:

Warning: failed to load Cython extensions.
See https://github.com/bsmurphy/PyKrige/issues/8 
Falling back to a pure python backend...

**Comment by rth** [comment]
@wind-chh PyKrige was uploaded on PiPy on 2015-10-24. Could you please try with the latest development version fom github:

      pip uninstall pykrige
      pip install git+https://github.com/bsmurphy/PyKrige.git

you would need to have the dependencies installed  including numpy, scipy, matplotlib, Cython (and possibly git).

**Comment by wind-chh** [comment]
I sent a pull request. It tested OK on my Fedora 23.

**Comment by rth** [comment]
Fixed in #21.
