### ISSUE TITLE
CircleCI

### ISSUE THREAD

**Issue by bsmurphy** [bsmurphy/PyKrige#53]
CircleCI seems to be having some issues running our ```setup.py``` script, since we check to ensure dependencies are installed before running the actual setup function. I added a ```circle.yml``` file to try to make sure that numpy/scipy/matplotlib are installed (via pip) before the setup script is run, but that seems to have lead to other problems (I think maybe because doing ```pip install matplotlib``` is problematic). 

@rth, @basaks, since you guys are better at this kind of stuff then I am, do you have any ideas?

**Comment by basaks** [comment]
Where can I find your circle.yaml?

**Comment by rth** [comment]
Thanks @bsmurphy . I have a Circle CI setup that should work, will make a PR...

**Comment by rth** [comment]
Fixed in https://github.com/bsmurphy/PyKrige/pull/61 i.e. Circle CI setup is no longer necessary for the documentation and can be removed.
