### ISSUE TITLE
Can't install manually with 'python setup.py install'

### ISSUE THREAD

**Issue by alexisrosuel** [bsmurphy/PyKrige#58]
Hi, 

I tried to clone this repositery and then do a 'python setup.py install', but it tells me that I don't have numpy installed. I double checked, and numpy is well installed and working on my computer.

Do someone knows the issues ? 

By the way, I do this because I want to try the regression kriging, which does not seem to be implemented in the pip version.

Thanks a lot for your help

**Comment by alexisrosuel** [comment]
Edit : I was installing on the wrong version of Python... I close this issue
Sorry

**Comment by bsmurphy** [comment]
Just a comment -- yes, regression kriging isn't currently in the latest version on PyPI. Cleaning up for a new release is the immediate task at hand, but I've been slowed down by other things. Hopefully in a few weeks I'll have the new version with regression kriging ready to put on PyPI.
