### ISSUE TITLE
Migrate from nose to pytest for unit tests

### ISSUE THREAD

**Issue by rth** [bsmurphy/PyKrige#64]
nose is not being developed anymore and we should probably migrate to pytest for unit tests (as most packages in the Python ecosystem have done or are in the process of doing).

This would allow to greatly simplify writing of unit tests, e.g. instead of 
```py
self.assertTrue(np.allclose(res, np.array([0.98, 1.05]), 0.01, 0.01))
```
one could simply write
```py
assert np.allclose(res, np.array([0.98, 1.05]), 0.01, 0.01)
```
and pytest would handle everything. Actually in this case,
```py
from numpy.testing import assert_allclose

assert_allclose(res, np.array([0.98, 1.05]), 0.01, 0.01)
```
would be even better.

**Note:** `numpy.testing` might still require to install nose (particularly for older numpy versions).

**Comment by bsmurphy** [comment]
I didn't know nose was no longer being supported... seemed like that was all the rage in Python testing when I started this a few years ago... anyways, sounds good, as we work on updates lets change the corresponding tests, that way eventually they'll all get updated
(unless someone wants to just take out a PR to change them all at once... but I think for now, with everything else going on, changing the tests as we work on related things might be best)
