### ISSUE TITLE
Improve docstrings formatting

### ISSUE THREAD

**Issue by rth** [bsmurphy/PyKrige#65]
Now that [online documentation](http://pykrige.readthedocs.io/en/latest/index.html) was setup, some effort to make sure all docstrings use a correct [numpy style formatting](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html) is necessary.

For instance, most methods under ["API reference"](http://pykrige.readthedocs.io/en/latest/api.html) of the documentation, are currently not very well rendered.

Any help on this would be greatly appreciated. Instructions on how to build the documentation locally can be found in https://github.com/bsmurphy/PyKrige/pull/48

**Comment by bsmurphy** [comment]
I'll be honest, as I was originally making the docs I didn't really have any idea about what kind of formatting was appropriate... so this definitely needs some work. Also might be a thing where gradual changes as they come up would be best...

**Comment by rth** [comment]
@bsmurphy +1 for gradual changes.  Also, it's not actually that much changes, just small formatting fixes: the docstrings are already really well documented, thanks, to your efforts )

**Comment by bsmurphy** [comment]
Closed with PR #84.
