### ISSUE TITLE
Benchmark results

### ISSUE THREAD

**Issue by yejingxin** [bsmurphy/PyKrige#7]
I tried to do benchmark run with gstat package in R, and I found there are differences between two outputs. Have you ever done similar experiments?
```R
library(gstat)
a <- read.table("http://www.stat.ucla.edu/~nchristo/statistics_c173_c273/kriging_11.txt", header=TRUE)
 x.range <- as.integer(range(a[,1]))
y.range <- as.integer(range(a[,2]))
grd <- expand.grid(x=seq(from=x.range[1], to=x.range[2], by=1),
                     y=seq(from=y.range[1], to=y.range[2], by=1))
m <- vgm(10, "Exp", 3.33, 0)
q1 <- krige(id="z", formula=z~1, data=a, newdata=data.frame(x=64, y=128), model = m,
            locations=~x+y)
```
```python
from pykrige.ok import OrdinaryKriging
import numpy as np
import pykrige.kriging_tools as kt

data = np.loadtxt('./kriging_11.txt', skiprows=1)

# vgm(psill, model, range, nugget)
# m <- vgm(10, "Exp", 3.33, 0)
#spherical - [sill, range, nugget]
OK = OrdinaryKriging(data[:, 0], data[:, 1], data[:, 2], variogram_model='exponential',
                     variogram_parameters = [10, 3.33, 0], 
                     verbose=False, enable_plotting=False)
z, ss = OK.execute('points', np.array([64]), np.array([128]))
print z
```
The prediction at (64, 128) I got 338.9828 from gstat and 363.59867058131033 from pykrige.

**Comment by yejingxin** [comment]
from pykrige.ok import OrdinaryKriging
import numpy as np
import pykrige.kriging_tools as kt

data = np.loadtxt('./kriging_11.txt', skiprows=1)

# vgm(psill, model, range, nugget)
# m <- vgm(10, "Exp", 3.33, 0)
#spherical - [sill, range, nugget]
OK = OrdinaryKriging(data[:, 0], data[:, 1], data[:, 2], variogram_model='exponential',
                     variogram_parameters = [10, 3.33, 0], 
                     verbose=False, enable_plotting=False)
z, ss = OK.execute('points', np.array([64]), np.array([128]))
print z

**Comment by bsmurphy** [comment]
PyKrige uses the variogram model definitions from Kitanidis (see reference in documentation), which differ slightly from those elsewhere. The functional forms are the same as those in gstat, but the scaling of variogram model parameters is slightly different. In the case of the exponential variogram model, Kitanidis defines the range as three times the length parameter; in gstat, the range is the same as the length parameter. The code below produces the result the you expect.

```python
from pykrige.ok import OrdinaryKriging
import numpy as np


def exp_vgm(params, dists):
    return (params[0] - params[2]) * (1. - np.exp(-dists/params[1])) + params[2]

data = np.array([[61., 139., 477.],
                 [63., 140., 696.],
                 [64., 129., 227.],
                 [68., 128., 646.],
                 [71., 140., 606.],
                 [73., 141., 791.],
                 [75., 128., 783.]])

ok = OrdinaryKriging(data[:, 0], data[:, 1], data[:, 2], variogram_model='custom',
                     variogram_function=exp_vgm, variogram_parameters=[10., 3.33, 0.])
z, ss = ok.execute('points', np.array([64.]), np.array([128.]))
print z
```

I mention this someplace in the documentation, although I should make it more clear in the future. I should also mention here that gstat uses the partial sill, whereas PyKrige uses the full sill in the variogram model functions (psill = sill - nugget).

**Comment by yejingxin** [comment]
thanks
