### ISSUE TITLE
The data with lon and lat  can be processed?

### ISSUE THREAD

**Issue by moonlighf** [bsmurphy/PyKrige#75]
Hello, i really want to know that how to process the data with lon and lat  . do i have to transport it to Projection coordinatesystem?  thank you

**Comment by bsmurphy** [comment]
There's a kwarg in the OK class to use lat/lon, it's the ```coordinates_type``` kwarg (see the doc string). Currently I believe that's only supported for 2D ordinary kriging, so if you want to use lat/lon for UK you'll have to project the coordinates yourself...

**Comment by bsmurphy** [comment]
With the v1.4 release (now on PyPI), you can use the ```coordinate_type``` kwarg in the OK class. It shouldn't be too difficult to extend this to the other kriging classes.
