### ISSUE TITLE
set coordinate_types

### ISSUE THREAD

**Issue by phigzen** [bsmurphy/PyKrige#81]
when i used OrdinaryKriging, i set" coordinate_types='geographic'", error occured" __init__() got an unexpected keyword argument 'coordinate_types". Are there some functions requiring imported?

**Comment by bsmurphy** [comment]
Can you double check your spelling of the kwarg, I think it's actually ```coordnates_type``` rather than ```coordinate_types```
Regardless, I just realized that the version on PyPI (1.3.2) doesn't include the geographic coordinates feature. So if you got the package from PyPI that'll also be a problem. I'll need to update the PyPI distro...

**Comment by IReese** [comment]
Hi All, Wondering the if the package from PyPi will be updated to 1.4.dev0.  I'm interested in doing some testing using the `coordinates_type` argument.  Perhaps there is a way I can build this from source?

**Comment by rth** [comment]
This should be fixed with the 1.4.0 release, please comment if it's not the case.
