### ISSUE TITLE
Error setting power variogram_parameters on Linux machines (different code?)

### ISSUE THREAD

**Issue by tex-downey** [bsmurphy/PyKrige#88]
I am trying to run a universal kriging class that I need to set the variogram_parameters on. This code works fine on a windows 10 machine but does not work on my Linux machines (Red Hat and Mint) . I ran:

`pip show PyKrige`

on both machines and got that pykrige is Version 1.3.2. The general code I am trying to run is this:

`krig = pykrige.uk.UniversalKriging(SEC_loc[:,0], SEC_loc[:,1], SEC_measured, 
                                                   variogram_model='power', drift_terms=[],
                                                   variogram_parameters={'scale': 2.21734644e-07, 
                                                                         'exponent': 1.10000000e+00, 
                                                                         'nugget': 2.85618110e-09})
`

If I remove the "variogram_parameters" parameter the code runs just fine. Here the values I am using for the parameters I took from a working class that is run without declaring the values. So I don't think it is the values of the parameters (I have tried several combinations) that is the problem but rather me trying to declare the parameters myself. The error I get is as follows:

```py
runfile('/Sensor_density/sensor_density_viogram.py', wdir='/Sensor_density')
testing noise 0, DSN 6, load 1
Traceback (most recent call last):

  File "<ipython-input-1-6b9745b15a7f>", line 1, in <module>
    runfile('/Sensor_density/sensor_density_viogram.py', wdir='/Sensor_density')

  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Documents/Sensor_density/sensor_density_viogram.py", line 167, in <module>
    'nugget': 2.85618110e-09})

  File "/anaconda3/lib/python3.6/site-packages/pykrige/uk.py", line 312, in __init__
    self.variogram_model_parameters)

  File "/anaconda3/lib/python3.6/site-packages/pykrige/core.py", line 387, in find_statistics
    z_, ss_ = krige(x[:n], y[:n], z[:n], (x[n], y[n]), variogram_function, variogram_model_parameters)

  File "/anaconda3/lib/python3.6/site-packages/pykrige/core.py", line 320, in krige
    a[:n, :n] = - variogram_function(variogram_model_parameters, d)

  File "/anaconda3/lib/python3.6/site-packages/pykrige/variogram_models.py", line 44, in power_variogram_model
    return float(params[0])*(dist**float(params[1])) + float(params[2])

KeyError: 0
```

I am not sure what KeyError:0 is but I figured someone would know this. Looking a little more at the functions I noticed my windows machine has a function of 

`def power_variogram_model(m, d):
    scale = float(m[0])
    exponent = float(m[1])
    nugget = float(m[2])
    return scale * d**exponent + nugget`

While my Linux machine has 

`def power_variogram_model(params, dist):
return float(params[0])*(dist**float(params[1])) + float(params[2])`

I am a little scared up update my Windows PyKrige as it is working but as both versions are the same I don't know what the problem could be. 
Best,
Austin.

**Comment by bsmurphy** [comment]
Sorry for the slow reply on this. Your Windows code looks to be at the most recent version, but your Linux code actually looks old. Have you tried updating the Linux code? Not sure why the Linux version would have that old variogram model module when it says it's up to date...

**Comment by bsmurphy** [comment]
We've just pushed the v1.4 release to PyPI, I'd recommend updating the codes on both your machines. Let me know if there's still a discrepancy between them once you've updated, as that will mean something really wrong is going on...

**Comment by rth** [comment]
This should be fixed with the latest release, closing, please comment if you still experience issues.
