### ISSUE TITLE
Add Github topics

### ISSUE THREAD

**Issue by rth** [bsmurphy/PyKrige#92]
It would be helpful to add some [Github topics](https://help.github.com/articles/classifying-your-repository-with-topics/) to help with discoverability of this repo. cc @bsmurphy

**Comment by bsmurphy** [comment]
Just added a few, can you think of any others that would be good?

**Comment by rth** [comment]
Maybe add a few more tags from https://github.com/juliohm/GeoStats.jl or https://github.com/madsjulia/Kriging.jl :
"geostatistics", "gaussian-processes", "variogram"  and possibly "covariance" and "spatial-analysis".

There is not need to have the "python" tag, because in Github when searching by tags one can filter by language anyway.

**Comment by bsmurphy** [comment]
Ah yes, good idea. I removed the python tag as well... just had it on there since GitHub recommended it

**Comment by rth** [comment]
Thanks!
