### ISSUE TITLE
Set coordinates type

### ISSUE THREAD

**Issue by Tahre92** [bsmurphy/PyKrige#93]
Hi
Im trying to do geometric ordinary kriging with the PyPi version but as you highlighted it does not work..how can i go about it then.in other words did manage to update it or you have other versions you can refer me to?..

**Comment by rth** [comment]
Please use the latest development version for now. It can be installed with,
```
pip install git+https://github.com/bsmurphy/PyKrige.git
```
we are in process of making the release on PyPi.

**Comment by Tahre92** [comment]
Hi
Thank you very much for the assistance will try download the latest
development version.
Kind regards
Tadi

**Comment by rth** [comment]
Closing see https://github.com/bsmurphy/PyKrige/issues/67#issuecomment-384283547
