### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by mariosgeo** [bsmurphy/PyKrige#96]
I have data of size [360,3]
I execute 

` OK = OrdinaryKriging(data[:, 0], data[:, 1], data[:, 2], variogram_model='linear',
                     verbose=False, enable_plotting=False)`

And then 
`z,SS=OK.execute('grid',gridx2,gridy2,backend='loop')`

Where gridx2 and gridy2 is of size [101,139]

It returns MemoryError. Is this really so big? I have 32gb ram

**Comment by rth** [comment]
Could you please post the full error traceback?

**Comment by mariosgeo** [comment]
`

z,SS=OK.execute('grid',gridx2,gridy2,backend='loop',n_closest_points=10) 

Traceback (most recent call last):

  File "<ipython-input-6-2e852f51bceb>", line 1, in <module>
    z,SS=OK.execute('grid',gridx2,gridy2,backend='loop',n_closest_points=10)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pykrige\ok.py", line 729, in execute
    bd, bd_idx = tree.query(xy_points, k=n_closest_points, eps=0.0)

  File "ckdtree.pyx", line 777, in scipy.spatial.ckdtree.cKDTree.query

MemoryError`

**Comment by mariosgeo** [comment]
z,SS=OK.execute('grid',gridx2,gridy2,backend='loop')
Traceback (most recent call last):

  File "<ipython-input-7-54fe5a4f9443>", line 1, in <module>
    z,SS=OK.execute('grid',gridx2,gridy2,backend='loop')

  File "C:\ProgramData\Anaconda3\lib\site-packages\pykrige\ok.py", line 684, in execute
    [self.anisotropy_angle]).T

  File "C:\ProgramData\Anaconda3\lib\site-packages\pykrige\core.py", line 163, in _adjust_for_anisotropy
    X_adj = np.dot(stretch, np.dot(rot_tot, X.T)).T

MemoryError

**Comment by mariosgeo** [comment]
The data matrix

612563	5.75703e+06	1.75755
612562	5.75702e+06	1.72362
612561	5.75702e+06	1.71634
612563	5.75702e+06	1.50745
612564	5.75702e+06	1.53882
612566	5.75703e+06	1.65002
612567	5.75703e+06	1.61034
612569	5.75703e+06	1.5088
612570	5.75703e+06	1.55751
612572	5.75703e+06	1.56478
612574	5.75703e+06	1.49234
612575	5.75703e+06	1.60552
612577	5.75703e+06	1.66596
612578	5.75704e+06	1.64777
612580	5.75704e+06	1.67514
612582	5.75704e+06	1.58309
612583	5.75704e+06	1.6797
612585	5.75704e+06	1.71214
612586	5.75704e+06	1.67761
612588	5.75704e+06	1.63073
612590	5.75704e+06	1.4484
612591	5.75704e+06	1.39129
612596	5.75705e+06	1.47611
612598	5.75705e+06	1.63387
612599	5.75705e+06	1.58546
612603	5.75705e+06	1.57611
612604	5.75705e+06	1.69346
612606	5.75705e+06	1.69302
612607	5.75706e+06	1.7185
612609	5.75706e+06	1.62232
612611	5.75706e+06	1.62665
612612	5.75706e+06	1.60853
612614	5.75706e+06	1.60358
612616	5.75706e+06	1.51587
612617	5.75706e+06	1.59693
612619	5.75706e+06	1.63083
612621	5.75706e+06	1.68833
612622	5.75706e+06	1.65447
612624	5.75707e+06	1.7195
612626	5.75707e+06	1.82588
612627	5.75707e+06	1.81723
612629	5.75707e+06	1.77004
612630	5.75707e+06	1.69037
612632	5.75707e+06	1.55811
612634	5.75707e+06	1.66978
612635	5.75707e+06	1.67127
612637	5.75708e+06	1.64748
612638	5.75708e+06	1.61055
612640	5.75708e+06	1.50447
612642	5.75708e+06	1.51348
612644	5.75708e+06	1.4813
612645	5.75708e+06	1.54407
612647	5.75708e+06	1.66483
612648	5.75708e+06	1.70131
612650	5.75708e+06	1.58218
612652	5.75708e+06	1.63799
612653	5.75709e+06	1.67669
612655	5.75709e+06	1.58939
612657	5.75709e+06	1.64611
612658	5.75709e+06	1.6653
612660	5.75709e+06	1.71408
612662	5.75709e+06	1.66096
612663	5.75709e+06	1.5783
612665	5.75709e+06	1.59084
612666	5.75709e+06	1.5506
612668	5.7571e+06	1.52101
612670	5.7571e+06	1.46731
612671	5.7571e+06	1.4368
612673	5.7571e+06	1.38828
612675	5.7571e+06	1.39375
612676	5.7571e+06	1.3955
612678	5.7571e+06	1.49638
612680	5.7571e+06	1.44855
612681	5.7571e+06	1.42878
612683	5.75711e+06	1.54531
612684	5.75711e+06	1.61658
612686	5.75711e+06	1.78817
612688	5.75711e+06	1.73183
612689	5.75711e+06	1.65992
612691	5.75711e+06	1.68242
612692	5.75711e+06	1.61469
612693	5.75711e+06	1.58995
612692	5.75711e+06	1.71366
612690	5.75711e+06	1.6816
612698	5.75712e+06	1.51561
612696	5.75712e+06	1.61204
612695	5.75712e+06	1.51706
612693	5.75712e+06	1.36773
612691	5.75711e+06	1.4312
612690	5.75711e+06	1.50065
612688	5.75711e+06	1.46776
612686	5.75711e+06	1.40002
612685	5.75711e+06	1.48728
612683	5.75711e+06	1.50529
612682	5.75711e+06	1.40295
612680	5.75711e+06	1.43823
612678	5.75711e+06	1.44483
612677	5.7571e+06	1.56253
612675	5.7571e+06	1.56015
612674	5.7571e+06	1.52088
612672	5.7571e+06	1.53224
612670	5.7571e+06	1.4823
612668	5.7571e+06	1.51812
612667	5.7571e+06	1.60649
612665	5.7571e+06	1.48416
612664	5.7571e+06	1.5432
612662	5.75709e+06	1.54962
612660	5.75709e+06	1.70578
612659	5.75709e+06	1.77561
612657	5.75709e+06	1.72123
612656	5.75709e+06	1.65495
612654	5.75709e+06	1.6217
612652	5.75709e+06	1.56396
612651	5.75709e+06	1.56194
612649	5.75709e+06	1.57043
612647	5.75708e+06	1.53529
612646	5.75708e+06	1.58286
612644	5.75708e+06	1.60217
612642	5.75708e+06	1.57066
612641	5.75708e+06	1.57113
612639	5.75708e+06	1.61268
612638	5.75708e+06	1.60119
612636	5.75708e+06	1.57066
612634	5.75708e+06	1.58737
612633	5.75708e+06	1.6467
612631	5.75707e+06	1.59824
612629	5.75707e+06	1.62511
612628	5.75707e+06	1.65686
612626	5.75707e+06	1.59737
612624	5.75707e+06	1.62737
612623	5.75707e+06	1.63337
612621	5.75707e+06	1.54407
612620	5.75707e+06	1.60927
612618	5.75707e+06	1.74162
612617	5.75706e+06	1.68269
612615	5.75706e+06	1.62221
612613	5.75706e+06	1.52711
612612	5.75706e+06	1.55558
612610	5.75706e+06	1.54555
612608	5.75706e+06	1.46449
612607	5.75706e+06	1.50961
612606	5.75706e+06	1.5168
612604	5.75705e+06	1.61268
612602	5.75705e+06	1.62418
612600	5.75705e+06	1.72354
612599	5.75705e+06	1.64018
612597	5.75705e+06	1.6766
612596	5.75705e+06	1.72378
612594	5.75705e+06	1.6787
612593	5.75705e+06	1.64807
612591	5.75705e+06	1.66829
612589	5.75705e+06	1.63849
612588	5.75704e+06	1.65254
612586	5.75704e+06	1.67733
612584	5.75704e+06	1.65099
612583	5.75704e+06	1.61941
612581	5.75704e+06	1.50732
612580	5.75704e+06	1.54133
612578	5.75704e+06	1.57761
612576	5.75704e+06	1.54728
612575	5.75704e+06	1.64933
612573	5.75703e+06	1.554
612572	5.75703e+06	1.60282
612570	5.75703e+06	1.54494
612568	5.75703e+06	1.57357
612567	5.75703e+06	1.61331
612567	5.75703e+06	1.63012
612567	5.75703e+06	1.80318
612569	5.75703e+06	1.69539
612567	5.75703e+06	1.7074
612568	5.75703e+06	1.83181
612568	5.75703e+06	1.79962
612562	5.75703e+06	1.92681
612560	5.75703e+06	1.87795
612560	5.75703e+06	1.92567
612561	5.75703e+06	1.67523
612562	5.75703e+06	1.67182
612564	5.75703e+06	1.66398
612566	5.75703e+06	1.55919
612567	5.75703e+06	1.46894
612569	5.75703e+06	1.50311
612571	5.75704e+06	1.6721
612572	5.75704e+06	1.68449
612574	5.75704e+06	1.66549
612575	5.75704e+06	1.65379
612577	5.75704e+06	1.64933
612579	5.75704e+06	1.59151
612580	5.75704e+06	1.57623
612582	5.75704e+06	1.57101
612584	5.75704e+06	1.5904
612585	5.75705e+06	1.50799
612587	5.75705e+06	1.55691
612589	5.75705e+06	1.61962
612590	5.75705e+06	1.66894
612592	5.75705e+06	1.66483
612593	5.75705e+06	1.59229
612595	5.75705e+06	1.62138
612597	5.75705e+06	1.61637
612598	5.75705e+06	1.63195
612600	5.75706e+06	1.69775
612601	5.75706e+06	1.72066
612603	5.75706e+06	1.75143
612605	5.75706e+06	1.76403
612606	5.75706e+06	1.65079
612606	5.75706e+06	1.71164
612608	5.75706e+06	1.76215
612609	5.75706e+06	1.78718
612611	5.75706e+06	1.77887
612612	5.75706e+06	1.69513
612614	5.75706e+06	1.74194
612616	5.75707e+06	1.75732
612617	5.75707e+06	1.76908
612619	5.75707e+06	1.71958
612620	5.75707e+06	1.76035
612622	5.75707e+06	1.8179
612624	5.75707e+06	1.89198
612625	5.75707e+06	1.94714
612627	5.75707e+06	1.90168
612629	5.75707e+06	1.89631
612630	5.75708e+06	1.68753
612632	5.75708e+06	1.63215
612634	5.75708e+06	1.53224
612635	5.75708e+06	1.46479
612637	5.75708e+06	1.46731
612638	5.75708e+06	1.48671
612640	5.75708e+06	1.46553
612642	5.75708e+06	1.45439
612643	5.75708e+06	1.44607
612645	5.75709e+06	1.52711
612647	5.75709e+06	1.63347
612648	5.75709e+06	1.50678
612650	5.75709e+06	1.51534
612652	5.75709e+06	1.56679
612653	5.75709e+06	1.48558
612655	5.75709e+06	1.48813
612656	5.75709e+06	1.48287
612657	5.75709e+06	1.5168
612657	5.75709e+06	1.58433
612658	5.75709e+06	1.554
612660	5.7571e+06	1.52427
612661	5.7571e+06	1.47885
612663	5.7571e+06	1.48982
612664	5.7571e+06	1.57322
612666	5.7571e+06	1.50338
612668	5.7571e+06	1.45667
612669	5.7571e+06	1.45591
612671	5.7571e+06	1.4707
612673	5.7571e+06	1.47276
612674	5.75710e+06	1.3948
612676	5.75711e+06	1.41547
612677	5.75711e+06	1.46776
612679	5.75711e+06	1.55279
612681	5.75711e+06	1.50583
612682	5.75711e+06	1.45834
612684	5.75711e+06	1.44917
612686	5.75711e+06	1.49651
612687	5.75711e+06	1.49541
612689	5.75711e+06	1.45163
612690	5.75712e+06	1.57669
612692	5.75712e+06	1.51415
612692	5.75711e+06	1.40535
612690	5.75711e+06	1.46642
612690	5.75711e+06	1.67724
612697	5.75712e+06	1.61731
612696	5.75712e+06	1.56265
612694	5.75712e+06	1.47159
612692	5.75712e+06	1.44778
612691	5.75712e+06	1.50623
612689	5.75712e+06	1.43056
612688	5.75712e+06	1.3941
612686	5.75712e+06	1.4777
612684	5.75711e+06	1.51135
612683	5.75711e+06	1.47349
612681	5.75711e+06	1.52336
612679	5.75711e+06	1.58127
612678	5.75711e+06	1.63286
612676	5.75711e+06	1.59748
612674	5.75711e+06	1.63639
612673	5.75711e+06	1.70346
612671	5.75711e+06	1.57357
612670	5.7571e+06	1.51614
612668	5.7571e+06	1.53058
612666	5.7571e+06	1.58546
612665	5.7571e+06	1.59561
612663	5.7571e+06	1.43313
612662	5.7571e+06	1.35238
612660	5.7571e+06	1.38417
612658	5.7571e+06	1.49136
612657	5.7571e+06	1.55291
612655	5.75709e+06	1.51574
612653	5.75709e+06	1.48259
612652	5.75709e+06	1.5168
612650	5.75709e+06	1.54357
612648	5.75709e+06	1.48401
612647	5.75709e+06	1.42455
612645	5.75709e+06	1.4387
612643	5.75709e+06	1.52231
612642	5.75709e+06	1.50024
612640	5.75708e+06	1.59923
612638	5.75708e+06	1.61013
612637	5.75708e+06	1.64207
612635	5.75708e+06	1.66661
612634	5.75708e+06	1.59627
612632	5.75708e+06	1.54642
612630	5.75708e+06	1.67906
612629	5.75708e+06	1.72843
612627	5.75708e+06	1.84658
612625	5.75708e+06	1.84516
612624	5.75707e+06	1.5311
612622	5.75707e+06	1.58252
612621	5.75707e+06	1.63104
612619	5.75707e+06	1.5989
612617	5.75707e+06	1.48813
612616	5.75707e+06	1.4915
612614	5.75707e+06	1.67825
612612	5.75707e+06	1.76133
612611	5.75707e+06	1.77779
612609	5.75706e+06	1.75853
612608	5.75706e+06	1.73472
612606	5.75706e+06	1.60574
612604	5.75706e+06	1.51574
612603	5.75706e+06	1.55715
612601	5.75706e+06	1.5867
612599	5.75706e+06	1.63306
612598	5.75706e+06	1.57403
612596	5.75706e+06	1.54058
612594	5.75705e+06	1.53135
612593	5.75705e+06	1.59879
612591	5.75705e+06	1.65734
612590	5.75705e+06	1.56348
612588	5.75705e+06	1.68655
612586	5.75705e+06	1.53339
612585	5.75705e+06	1.53466
612583	5.75705e+06	1.41246
612581	5.75705e+06	1.43712
612580	5.75704e+06	1.43902
612578	5.75704e+06	1.46075
612576	5.75704e+06	1.70157
612575	5.75704e+06	1.71433
612573	5.75704e+06	1.59306
612572	5.75704e+06	1.50745
612570	5.75704e+06	1.58422
612568	5.75704e+06	1.51838
612567	5.75704e+06	1.53046
612565	5.75703e+06	1.57749
612563	5.75703e+06	1.5168
612562	5.75703e+06	1.48015
612560	5.75703e+06	1.53122
612560	5.75703e+06	1.52969
612561	5.75703e+06	1.47596
612563	5.75703e+06	1.5636
612563	5.75703e+06	1.59295
612563	5.75703e+06	1.80733

**Comment by mariosgeo** [comment]
gridx2,gridy2=np.meshgrid(np.arange(   np.min(data[:,0]),     np.max(data[:,0]),1   )   ,  np.arange(np.min(data[:,1]),np.max(data[:,1]),1))

**Comment by mariosgeo** [comment]
The data would have been better if they were rotated, but oh well :)

**Comment by mariosgeo** [comment]
Never mind, I figure it out. I am providing the whole gridx and not the first row.

You can close the issue.

**Comment by rth** [comment]
OK, makes sense. Thanks for follow up.

**Comment by leomiquelutti** [comment]
Dear @rth,

I get a similar error when executing line 
`uk = OrdinaryKriging(x, y, bz, variogram_model='linear', verbose=False, enable_plotting=False)`

The error is

> C:\Users\Leonardo\AppData\Local\conda\conda\envs\fatiando\lib\site-packages\fatiando\vis\mpl.py:76: UserWarning: This module will be removed in v0.6. We recommend the use of matplotlib.pyplot module directly. Some of the fatiando specific functions will remain.
  "specific functions will remain.")
Traceback (most recent call last):
  File "c:\Users\Leonardo\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\Leonardo\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\Leonardo\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\Leonardo\AppData\Local\conda\conda\envs\fatiando\lib\runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "C:\Users\Leonardo\AppData\Local\conda\conda\envs\fatiando\lib\runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "C:\Users\Leonardo\AppData\Local\conda\conda\envs\fatiando\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Users\Leonardo\OneDrive\Documentos\Python Scripts\kimberlito castelhana\land_mag.py", line 57, in <module>
    uk = OrdinaryKriging(x, y, bz, variogram_model='linear', verbose=False, enable_plotting=False)
  File "C:\Users\Leonardo\AppData\Local\conda\conda\envs\fatiando\lib\site-packages\pykrige\ok.py", line 239, in __init__
    weight, self.coordinates_type)
  File "C:\Users\Leonardo\AppData\Local\conda\conda\envs\fatiando\lib\site-packages\pykrige\core.py", line 391, in _initialize_variogram_model
    d = pdist(X, metric='euclidean')
  File "C:\Users\Leonardo\AppData\Local\conda\conda\envs\fatiando\lib\site-packages\scipy\spatial\distance.py", line 1877, in pdist
    dm = np.empty((m * (m - 1)) // 2, dtype=np.double)
MemoryError

`x`, `y` and `bz` are of size 15852. Is it that my arrays are too big? Any idea on how to get around this problem?
